name: palnt_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  android_alarm_manager_plus: 3.0.4
  auto_size_text: null
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartz: null
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: 16.2.0
  flutter_localizations:
    sdk: flutter
  gap: null
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  image_picker: ^1.0.7
  internet_connection_checker: null
  intl: null
  loading_animation_widget: null
  page_transition: null
  provider: ^6.1.2
  shared_preferences: null
  timezone: ^0.9.4


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
